Adding ability to target ref and tests

diff --git a/git-past-amend b/git-past-amend
--- a/git-past-amend
+++ b/git-past-amend
@@ -4,12 +4,15 @@
 
 set -e
 
-if ! [[ $1 =~ ^[1-9][0-9]*$ ]] ; then
-   echo "Error: Argument must be an integer bigger than 0." >&2
-   exit 1
+if [[ $1 =~ ^[1-9][0-9]*$ ]] ; then
+    if [ $1 -gt 20 ] ; then
+        echo "Error: Can't specify a depth bigger than 20, please specify ref directly." >&2
+    exit 1
+    fi
+    commit_to_amend=$(git rev-parse --verify HEAD~$1)
+else
+    commit_to_amend=$(git rev-parse --verify $1)
 fi
-
-depth=$1
 
 if (git diff --cached --quiet) ; then # If nothing is staged
     git add --all
@@ -24,11 +27,11 @@ if (git diff --cached --quiet) ; then # If nothing is staged
 fi
 
 git stash save
-git checkout HEAD~$depth
+git checkout $commit_to_amend --detach
 git stash pop
 git add --all
 git commit --amend --no-edit
 rebase_target=$(git rev-parse --verify HEAD)
-git checkout - 
+git checkout -
 git rebase $rebase_target
     
